### PR TITLE
Update, alphabetize, and remove duplicates

### PR DESCRIPTION
**Pull request by SomeGuyNamedDavid**

### CODE REVIEW

**Comment by rauenzi** [comment]
Alphabetizing doesn't do anything for the system really, and this PR adds some additional blacklisted emojis that are meant to be available to use.

**Comment by SomeGuyNamedDavid** [comment]
I've been adding any I came across that are formatted like a regular word (first letter caps, other letters lowercase) and might feasibly come up unintentionally in normal conversation. If there are any that you think aren't problematic enough to belong on the blacklist, feel free to remove them, or point them out and I'll remove.

(Alphabetization was just to make the list more conveniently human-readable.)

**Comment by yaniser** [comment]
j ai rien compris a se site quelqu un peut m aider ?

**Comment by rauenzi** [comment]
Several of these are not something that would come up in conversations which is what the default blacklist is meant for. I have added a couple to the main list.

**Pull request closed without merging**
