### PR TITLE
add reference to original on monkeyPatched functions

### PR DESCRIPTION
**Pull request by Inve1951**
L1270

### CODE REVIEW

**Comment by Inve1951** [comment]
diff at https://github.com/rauenzi/BetterDiscordApp/pull/150/files?w=1

**Comment by rauenzi** [comment]
Why you messin' with my whitespace dawg?

**Comment by Inve1951** [comment]
atom trims all trailing whitespace on save

**Comment by rauenzi** [comment]
Not configurable? gross

**Pull request merged**
