### PR TITLE
Added Japanese translation

### PR DESCRIPTION
**Pull request by Kazanami**
Send Pull Request for the first time.

I have added Japanese translation of BetterDiscord.
I do not know how to write a little, and I am a little worried about whether it is good.

### CODE REVIEW

**Comment by Kazanami** [comment]
I was sorry.
Which line is applicable?

**Comment by intrnl** [comment]
Using the web interface should tell you the line that I commented, but I'll tell you here anyway.

Line 453:
_時間を24時間表記に変更します。**Hides channels when in minimal mode**_

**Comment by Kazanami** [comment]
I found the corresponding line. I will fix it soon.
Thank you very much.

Also, I am not familiar with Github, but if I push the updated source code, will this Pull Request be updated automatically ...?

**Comment by intrnl** [comment]
Yes, if you push the commit to the same branch, it will be in this pull request.

**Comment by Kazanami** [comment]
Understood.
Thank you very much for your reference

**Comment by rauenzi** [comment]
Hi @Kazanami , with the strings nearly finalized, would you mind updating the Japanese translation to match the [English](https://github.com/rauenzi/BetterDiscordApp/blob/stable/assets/locales/en.json)?

**Comment by rauenzi** [comment]
@Kazanami Would you mind updating the translations through POEditor by joining here https://poeditor.com/join/project?hash=nRljcnV0ET this is the recommended way now. You will also be able to check periodically in case there are new strings added as BD adds new features.

**Pull request merged**
