### PR TITLE
Update French translation

### PR DESCRIPTION
**Pull request by xerta555**

### CODE REVIEW

**Comment by rauenzi** [comment]
@xerta555 Would you mind updating the translations through POEditor by joining here https://poeditor.com/join/project?hash=nRljcnV0ET this is the recommended way now. You will also be able to check periodically in case there are new strings added as BD adds new features.

**Comment by xerta555** [comment]
> @xerta555 Would you mind updating the translations through POEditor by joining here [poeditor.com/join/project?hash=nRljcnV0ET](https://poeditor.com/join/project?hash=nRljcnV0ET) this is the recommended way now. You will also be able to check periodically in case there are new strings added as BD adds new features.

I have translate all strings for the French translation, but idk if it save in real-time as idk this translation website.

**Comment by rauenzi** [comment]
Yes the website saves in realtime then I trigger github updates from the website. Thanks for taking the time to translate!

**Comment by xerta555** [comment]
> Yes the website saves in realtime then I trigger github updates from the website. Thanks for taking the time to translate!

Ok nice so here we go and np.
And for my question ?(https://github.com/rauenzi/BetterDiscordApp/pull/649#issuecomment-815534012)

**Pull request closed without merging**
