### PR TITLE
add simplified chinese translation

### PR DESCRIPTION
**Pull request by sunxyw**

### CODE REVIEW

**Comment by rauenzi** [comment]
Can you add your translation to our crowd translations platforms? https://poeditor.com/join/project?hash=nRljcnV0ET

**Comment by sunxyw** [comment]
Sure, I will do it later.-------- 原始電子郵件 --------寄件者： Zack ***@***.***>日期： 2021年4月16日 週五 05:00收件者： rauenzi/BetterDiscordApp ***@***.***>副本： sunxyw ***@***.***>, Author ***@***.***>主旨： Re: [rauenzi/BetterDiscordApp] add simplified chinese translation (#703)
Can you add your translation to our crowd translations platforms? https://poeditor.com/join/project?hash=nRljcnV0ET

**Comment by rauenzi** [comment]
Thanks! I saw you signed up on there, should be able to just import this file

**Comment by sunxyw** [comment]
I have submitted a translation on POEditor.

**Comment by rauenzi** [comment]
Thanks for doing that!

**Pull request closed without merging**
