### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by xerta555**

### CODE REVIEW

**Comment by rauenzi** [comment]
Thank you for adding this, however it does not have 100% coverage. If you'd like to update the rest of the translations, we are using POEditor to do so

**Comment by xerta555** [comment]
> Thank you for adding this, however it does not have 100% coverage. If you'd like to update the rest of the translations, we are using POEditor to do so

I am in the process of updating it, i realized it by comparing the number of lines with the English version.

Just for my information, has the "Copy Selector" function been removed or replaced with a similar one? It was very useful to me, hence my question.

**Comment by rauenzi** [comment]
Copy selector has been removed in favor of the one provided by chromium. In the elements panel, right click the element and you will have an option to copy selector there.

**Comment by xerta555** [comment]
> Copy selector has been removed in favor of the one provided by chromium. In the elements panel, right click the element and you will have an option to copy selector there.

Ah ok, but if i want to edit CSS properties of BETTERDISCORD settings in the settings panel, how can i get the CSS targets so?

**Comment by rauenzi** [comment]
You can also do that in the elements panel of devtools (ctrl+shift+i)

**Comment by Tropix126** [comment]
> > Copy selector has been removed in favor of the one provided by chromium. In the elements panel, right click the element and you will have an option to copy selector there.
> 
> Ah ok, but if i want to edit CSS properties of BETTERDISCORD settings in the settings panel, how can i get the CSS targets so?


https://user-images.githubusercontent.com/42101043/114081055-b9270280-9871-11eb-8e03-a3072a26033a.mp4

**Comment by xerta555** [comment]
> u can also do that in the elements panel of devtools (ctrl+shift+i)

Ok niiice u have directly include the in-build dev tools of Chromium in Discord.

Thx for your work 👍🏻

**Pull request merged**
