### PR TITLE
Changed how link for Linux looks

### PR DESCRIPTION
**Pull request by MinerChAI**

### CODE REVIEW

**Comment by rauenzi** [comment]
Why

**Comment by MinerChAI** [comment]
1) Looks better
2) When on https://rauenzi.github.io/BetterDiscordApp/ browser doesn’t recognize it as link

**Comment by rauenzi** [comment]
That's not how this GitHub should be accessed or linked so that's fine.

**Comment by KaKi87** [comment]
You should disable the website from the GitHub Pages section in your repository's settings then.
Besides, this feature is not enabled by default so you must have thought about making it accessible in that way, some day.

**Pull request closed without merging**
