### PR TITLE
Fix injection in linux

### LINKED ISSUE #789: [Bug] Wrong injection location for inject script on linux
**Describe the Bug**

After building and injecting BetterDiscord using `npm run build` and `npm run inject` Discord crashes with the following message:
```
A JavaScript error occurred in the main process
Uncaught Exception:                                                                                                                      
Error: Session can only be received when app is ready                                                                                    
    at Object.get [as defaultSession] (electron/js2c/browser_init.js:117:366)
    at Function.remove (webpack-internal:///./src/modules/csp.js:11:64)
    at eval (webpack-internal:///./src/index.js:34:60)
    at Object../src/index.js (/home/mm2pl/git/BetterDiscordApp/dist/injector.js:29:1)
    at __webpack_require__ (/home/mm2pl/git/BetterDiscordApp/dist/injector.js:142:41)                                                   
    at /home/mm2pl/git/BetterDiscordApp/dist/injector.js:194:37
    at Object.<anonymous> (/home/mm2pl/git/BetterDiscordApp/dist/injector.js:196:12)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
```

`discordPath` was overridden to be the true path for my system (`~/Discord/resources`). BD was cloned to `~/git/BetterDiscordApp`.

**To Reproduce**

It just doesn't work, I have no idea if this bug is reproducible.

**Expected Behavior**

Discord actually working.

**Screenshots**

N/A

**Discord Version**

Stable

**Additional Context**

I'm using Ubuntu 20.04.1 LTS (Focal Fossa)

<details>
<summary>Contents of `~/git/BetterDiscordApp/dist`:</summary>

```
drwxrwxr-x  2 mm2pl mm2pl 4,0K maj 19 09:11 .
drwxrwxr-x 13 mm2pl mm2pl 4,0K maj 19 09:32 ..
-rw-rw-r--  1 mm2pl mm2pl  55K maj 19 09:11 injector.js
-rw-rw-r--  1 mm2pl mm2pl   45 maj 19 09:11 package.json
-rw-rw-r--  1 mm2pl mm2pl 1,1K maj 19 09:11 preload.js
-rw-rw-r--  1 mm2pl mm2pl 1,9M maj 19 09:32 renderer.js
```

[injector.js](https://kotmisia.pl/haste/raw/6fho2MlUWln4GzA)
[package.json](https://kotmisia.pl/haste/raw/U8yYl9Z3hKFAWgr)
[preload.js](https://kotmisia.pl/haste/raw/OEIh64owL7qdQS3)
[renderer.js](https://kotmisia.pl/haste/raw/Q7kFuo4UoO0I7kr)

</details>
Update: I managed to get the installer working but not `npm run ...`

### LINKED ISSUE #791: [Bug] crash at startup after injecting from source
**Describe the Bug**
Discord crashes with JavaScript error "Session can only be received when app is ready" after injecting.

**To Reproduce**
Follow steps in README under "Manual installation"

**Expected Behavior**
Discord starts correctly.

**Screenshots**
Screenshot wouldn't be helpful, but here's the traceback:
```
spiral@computer:~/BetterDiscordApp$ discord
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Session can only be received when app is ready
    at Object.get [as defaultSession] (electron/js2c/browser_init.js:117:366)
    at Function.remove (webpack-internal:///./src/modules/csp.js:11:64)
    at eval (webpack-internal:///./src/index.js:34:60)
    at Object../src/index.js (/home/spiral/BetterDiscordApp/dist/injector.js:29:1)
    at __webpack_require__ (/home/spiral/BetterDiscordApp/dist/injector.js:142:41)
    at /home/spiral/BetterDiscordApp/dist/injector.js:194:37
    at Object.<anonymous> (/home/spiral/BetterDiscordApp/dist/injector.js:196:12)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
```

**Discord Version**
Stable

**Additional Context**
Linux Mint 20.1

### PR DESCRIPTION
**Pull request by aarons-dev**
Closes #789 & Closes #791 

This pull request fixes the injecting on Linux, for the error message "Session can only be received when app is ready"

### CODE REVIEW

**Comment by rauenzi** [comment]
This is not the direction to fix this. As I said in the issues you mentioned the `inject` script is wrong and injecting to the wrong location.

**Comment by aarons-dev** [comment]
Therefor, why does it work? I've tested it 5-6 times, and it works.

**Comment by rauenzi** [comment]
Because this makes it work for the erroneous injection--the injection method we _are not using_ going forward with BD on Linux.

**Comment by aarons-dev** [comment]
it's okay, thanks for explaining and sorry for waisting your time.

**Comment by rauenzi** [comment]
No worries at all, I explored this type of injection on Linux myself. It works great if it's a regular Discord install that you have control over. But in many cases people are installing via app managers, snap, and flatpak which won't be compatible with this injection method. 

So in order to prepare for wider Linux support, we changed back to this type of injection. I will update the `inject` script soon so you can see it, but in the interim, you can take a look at the installer's method.

**Pull request closed without merging**
