### PR TITLE
More documentation improvements

### PR DESCRIPTION
**Pull request by Zerthox**
This improves consistency like capitalization or punctuation marks and fixes some typos. It also adds missing documentation for parameters & return types and fixes the incorrect description of the `UI` class.

### CODE REVIEW

**Comment by Zerthox** [comment]
Just wanted to mention: BetterDiscord/docs#6 has been open for months. You might want to check PRs on [BetterDiscord/docs](https:://github.com/BetterDiscord/docs) in general, there's open PRs fixing typos etc. from other people as well.

**Comment by rauenzi** [comment]
I'll review this soon, definitely some changes/comments to be made here. As for your other comment, I have most definitely seen the PRs there, but they are extremely minor and low priority compared to other things.

**Comment by rauenzi** [comment]
I think I prefer not forcing parameter and return value descriptions to end with periods, they are often sentence fragments so it doesn't fit.

This also still mixes using ` - ` as a separator between name and description, it should be one way or the other if you're making sweeping changes. Same with mixing capitalization of primitives.

**Comment by rauenzi** [comment]
I appreciate the effort and time you put into this one, Zerthox!

**Pull request merged**
