### PR TITLE
Added :not([id]) because of whiny plugin devs

### PR DESCRIPTION
**Pull request by mwittrien**

### CODE REVIEW

**Comment by TheDarkBomber** [comment]
@rauenzi hello?

**Comment by rauenzi** [comment]
@TheDarkBomber ?

**Comment by TheDarkBomber** [comment]
@rauenzi are you going to merge this?

**Comment by rauenzi** [comment]
Not sure that I will, why?

**Comment by TheDarkBomber** [comment]
@rauenzi It would fix some plugins

**Comment by rauenzi** [comment]
Can you give any examples of affected plugins?

**Comment by TheDarkBomber** [comment]
@rauenzi https://github.com/Inve1951/BetterDiscordStuff/blob/master/plugins/AvatarHover.plugin.js

**Comment by rauenzi** [comment]
Yes that is probably the only one affected by this due to the really odd programming used there.

**Comment by intrnl** [comment]
Jiiks' Clock plugin is also affected

**Comment by rauenzi** [comment]
Again a case of bad practices

**Pull request closed without merging**
