### PR TITLE
Translate BetterDiscord strings into Polish

### PR DESCRIPTION
**Pull request by TPGPL**

### CODE REVIEW

**Comment by intrnl** [comment]
You are doing it in the wrong place, [this is where localized strings goes](https://github.com/rauenzi/BetterDiscordApp/tree/development/data/locales)

**Comment by TPGPL** [comment]
mb i based on the old translation PRs

**Comment by TPGPL** [comment]
fixed i guess

**Comment by RazerMoon** [comment]
nice translation

**Comment by TPGPL** [comment]
@rauenzi are there any plans on merging this one?

**Comment by rauenzi** [comment]
There are, but the rewrite of BBD has been on hold for a bit so I didn't want to accept PRs for it right now. Also, with the rewrite still not being near completion, strings are being added, removed, and changed as I go. So I'd rather wait until the strings are in a less-changing state before accepting translations. I left it open so it didn't get lost and when the strings were closer to finalized I could ask you to double check your translations.

**Comment by rauenzi** [comment]
@TPGPL You can add your translations through POEditor by joining here https://poeditor.com/join/project?hash=nRljcnV0ET this is the recommended way now. You will also be able to check periodically in case there are new strings added as BD adds new features.

**Pull request closed without merging**
